### ISSUE TITLE
Bug en el plugin de Infocoordinates

### ISSUE THREAD

**Issue by aurieTech** [IGN-CNIG/API-CNIG#12]
1. Una vez abierto el popup de Infocoordinates, aunque esté cerrado el clicar en el mapa sigue generando puntos. 
2. También, si creas un nuevo punto, y cierras el popup, al abrirlo los puntos se añaden de 3 en 3.

**Comment by IngenieroGeomatico** [comment]
Muy buenas @khachimarur80 , gracias por tu comentario y utilizar la API-CNIG.

Hemos estado intentando replicar el caso de uso que nos comentas pero no hemos sido capaces de replicarlo.

¿Podrías ponernos los pasos que has seguido o dónde lo estás usando? Las pruebas las hemos realizado en Iberpix: https://www.ign.es/iberpix/ y en el propio test de la extensión infocoordinates: https://componentes-desarrollo.cnig.es/api-core/infocoordinates.jsp?language=es

Esperamos tu retroalimentación, un saludo.

**Comment by khachimarur80** [comment]
Buenos días, Ya he encontrado la razón del bug. Estoy usando la API dentro de una aplicación de Vue. Estoy inicializando el mapa y el plugin siguiendo los ejemplos de la documentación. El entorno de uso es un componente separado en Vue.js. La importación es la indicada en la documentación usando CDN. Adjunto también el código donde inicializo y utilizo el plugin. Adjunto los dos componentes, uno con el error y el otro sin. La causa del error al parecer es un “prop” del componente llamado “points”. Este por alguna razón causa un conflicto con el plugin de “infoCoordinates”. No sé si debería hacer pull request para añadir esto a la documentación. La verdad es que como desarrollador hay bastantes puntos en la documentación que no quedan del todo claros, como la declaración de estilos para los objectos Feature, y a veces me saltan algunos errores. Quizás también es  debido al entorno de desarrollo. Convendría que estuviese disponible para npm o integrado con otros frameworks frontend como Vue o React. Voy a tratar de informarme al máximo para poder ir aportando lo que pueda, muchas gracias. Un saludo Enviado desde Correo para Windows De: IngenieroGeomaticoEnviado: miércoles, 28 de febrero de 2024 11:43Para: IGN-CNIG/API-CNIGCC: khachimarur80; MentionAsunto: Re: [IGN-CNIG/API-CNIG] Bug en el plugin de Infocoordinates (Issue #12) Muy buenas @khachimarur80 , gracias por tu comentario y utilizar la API-CNIG.Hemos estado intentando replicar el caso de uso que nos comentas pero no hemos sido capaces de replicarlo.¿Podrías ponernos los pasos que has seguido o dónde lo estás usando? Las pruebas las hemos realizado en Iberpix: https://www.ign.es/iberpix/ y en el propio test de la extensión infocoordinates: https://componentes-desarrollo.cnig.es/api-core/infocoordinates.jsp?language=esEsperamos tu retroalimentación, un saludo.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by IngenieroGeomatico** [comment]
Buenas de nuevo:

No he podido ver los adjuntos que indicas, pero me alegro que hayas encontrado la causa del problema.

Cualquier punto de mejora que nos quieras ofreces, estamos abiertos a sugerencias o P.R.

¡Un saludo y muchas gracias!
